export const BAG_REVIEWS = [
  {
    id: 1,
    productId: 1,
    user: "sj*****",
    rating: 1,
    content: "진짜 예쁜 빨간 가방이에요! 튼튼하고 수납력도 좋아요.",
    date: "2024-11-28",
  },
  {
    id: 2,
    productId: 1,
    user: "xy*****",
    rating: 2,
    content: "지퍼 부분이 부드러워서 열고 닫기 편해요.",
    date: "2024-12-20",
  },
  {
    id: 3,
    productId: 1,
    user: "qb*****",
    rating: 4,
    content: "가격 대비 퀄리티가 좋아요!",
    date: "2024-10-22",
  },
  {
    id: 4,
    productId: 1,
    user: "xs*****",
    rating: 2,
    content: "배송도 빠르고 포장도 꼼꼼했어요.",
    date: "2025-05-03",
  },
  {
    id: 5,
    productId: 1,
    user: "ud*****",
    rating: 3,
    content: "사진보다 실물이 더 예뻐요.",
    date: "2024-08-20",
  },
  {
    id: 6,
    productId: 1,
    user: "zc*****",
    rating: 3,
    content: "지퍼 부분이 부드러워서 열고 닫기 편해요.",
    date: "2024-07-17",
  },
  {
    id: 7,
    productId: 1,
    user: "cy*****",
    rating: 5,
    content: "가격 대비 퀄리티가 좋아요!",
    date: "2024-06-29",
  },
  {
    id: 8,
    productId: 1,
    user: "cj*****",
    rating: 5,
    content: "가죽 질감이 고급스럽고 색감도 마음에 들어요.",
    date: "2024-09-09",
  },
  {
    id: 9,
    productId: 1,
    user: "zh*****",
    rating: 3,
    content: "진짜 예쁜 빨간 가방이에요! 튼튼하고 수납력도 좋아요.",
    date: "2024-05-31",
  },
  {
    id: 10,
    productId: 1,
    user: "iv*****",
    rating: 1,
    content: "선물용으로 구매했는데 만족도가 높아요.",
    date: "2025-05-04",
  },
  {
    id: 11,
    productId: 1,
    user: "hg*****",
    rating: 5,
    content: "가죽 질감이 고급스럽고 색감도 마음에 들어요.",
    date: "2024-07-10",
  },
  {
    id: 12,
    productId: 1,
    user: "wv*****",
    rating: 1,
    content: "배송도 빠르고 포장도 꼼꼼했어요.",
    date: "2025-01-30",
  },
  {
    id: 13,
    productId: 1,
    user: "oy*****",
    rating: 2,
    content: "가죽 질감이 고급스럽고 색감도 마음에 들어요.",
    date: "2025-01-02",
  },
  {
    id: 14,
    productId: 1,
    user: "hl*****",
    rating: 4,
    content: "선물용으로 구매했는데 만족도가 높아요.",
    date: "2025-02-01",
  },
  {
    id: 15,
    productId: 1,
    user: "sc*****",
    rating: 1,
    content: "지퍼 부분이 부드러워서 열고 닫기 편해요.",
    date: "2025-02-02",
  },
  {
    id: 16,
    productId: 1,
    user: "qe*****",
    rating: 1,
    content: "옷이랑 잘 어울려서 자주 들게 돼요.",
    date: "2024-11-12",
  },
  {
    id: 17,
    productId: 1,
    user: "ef*****",
    rating: 2,
    content: "사진보다 실물이 더 예뻐요.",
    date: "2024-11-30",
  },
  {
    id: 18,
    productId: 1,
    user: "rj*****",
    rating: 1,
    content: "배송도 빠르고 포장도 꼼꼼했어요.",
    date: "2024-06-01",
  },
  {
    id: 19,
    productId: 1,
    user: "zi*****",
    rating: 5,
    content: "가격 대비 퀄리티가 좋아요!",
    date: "2025-01-08",
  },
  {
    id: 20,
    productId: 1,
    user: "fs*****",
    rating: 3,
    content: "가볍고 편해서 데일리로 딱입니다.",
    date: "2025-01-10",
  },
  {
    id: 21,
    productId: 1,
    user: "go*****",
    rating: 2,
    content: "배송도 빠르고 포장도 꼼꼼했어요.",
    date: "2025-02-20",
  },
  {
    id: 22,
    productId: 1,
    user: "ki*****",
    rating: 4,
    content: "지퍼 부분이 부드러워서 열고 닫기 편해요.",
    date: "2024-11-24",
  },
  {
    id: 23,
    productId: 1,
    user: "ip*****",
    rating: 3,
    content: "지퍼 부분이 부드러워서 열고 닫기 편해요.",
    date: "2025-05-03",
  },
  {
    id: 24,
    productId: 1,
    user: "jv*****",
    rating: 2,
    content: "가격 대비 퀄리티가 좋아요!",
    date: "2024-12-12",
  },
  {
    id: 25,
    productId: 1,
    user: "ni*****",
    rating: 4,
    content: "가볍고 편해서 데일리로 딱입니다.",
    date: "2025-05-10",
  },
  {
    id: 26,
    productId: 1,
    user: "ww*****",
    rating: 4,
    content: "가죽 질감이 고급스럽고 색감도 마음에 들어요.",
    date: "2024-11-12",
  },
  {
    id: 27,
    productId: 1,
    user: "oz*****",
    rating: 5,
    content: "가죽 질감이 고급스럽고 색감도 마음에 들어요.",
    date: "2025-02-23",
  },
  {
    id: 28,
    productId: 1,
    user: "bk*****",
    rating: 2,
    content: "가죽 질감이 고급스럽고 색감도 마음에 들어요.",
    date: "2025-04-05",
  },
  {
    id: 29,
    productId: 1,
    user: "ii*****",
    rating: 2,
    content: "옷이랑 잘 어울려서 자주 들게 돼요.",
    date: "2024-08-05",
  },
  {
    id: 30,
    productId: 1,
    user: "ge*****",
    rating: 3,
    content: "배송도 빠르고 포장도 꼼꼼했어요.",
    date: "2024-07-03",
  },
  {
    id: 31,
    productId: 1,
    user: "dx*****",
    rating: 3,
    content: "가볍고 편해서 데일리로 딱입니다.",
    date: "2024-11-04",
  },
  {
    id: 32,
    productId: 1,
    user: "fw*****",
    rating: 4,
    content: "선물용으로 구매했는데 만족도가 높아요.",
    date: "2025-03-22",
  },
  {
    id: 33,
    productId: 1,
    user: "kw*****",
    rating: 1,
    content: "옷이랑 잘 어울려서 자주 들게 돼요.",
    date: "2024-07-30",
  },
  {
    id: 34,
    productId: 1,
    user: "qw*****",
    rating: 4,
    content: "가격 대비 퀄리티가 좋아요!",
    date: "2025-02-15",
  },
  {
    id: 35,
    productId: 1,
    user: "lf*****",
    rating: 5,
    content: "부담 없이 들기 좋은 스타일이에요.",
    date: "2024-09-20",
  },
  {
    id: 36,
    productId: 1,
    user: "tr*****",
    rating: 1,
    content: "가격 대비 퀄리티가 좋아요!",
    date: "2025-03-26",
  },
  {
    id: 37,
    productId: 1,
    user: "up*****",
    rating: 1,
    content: "사진보다 실물이 더 예뻐요.",
    date: "2025-03-01",
  },
  {
    id: 38,
    productId: 1,
    user: "sz*****",
    rating: 2,
    content: "선물용으로 구매했는데 만족도가 높아요.",
    date: "2024-08-28",
  },
  {
    id: 39,
    productId: 1,
    user: "hh*****",
    rating: 1,
    content: "배송도 빠르고 포장도 꼼꼼했어요.",
    date: "2024-10-18",
  },
  {
    id: 40,
    productId: 1,
    user: "wn*****",
    rating: 2,
    content: "가죽 질감이 고급스럽고 색감도 마음에 들어요.",
    date: "2025-01-01",
  },
  {
    id: 41,
    productId: 1,
    user: "hu*****",
    rating: 4,
    content: "가죽 질감이 고급스럽고 색감도 마음에 들어요.",
    date: "2025-04-17",
  },
  {
    id: 42,
    productId: 1,
    user: "um*****",
    rating: 2,
    content: "배송도 빠르고 포장도 꼼꼼했어요.",
    date: "2024-05-17",
  },
  {
    id: 43,
    productId: 1,
    user: "lt*****",
    rating: 4,
    content: "가볍고 편해서 데일리로 딱입니다.",
    date: "2024-12-20",
  },
  {
    id: 44,
    productId: 1,
    user: "hf*****",
    rating: 1,
    content: "가볍고 편해서 데일리로 딱입니다.",
    date: "2024-09-11",
  },
  {
    id: 45,
    productId: 1,
    user: "ax*****",
    rating: 4,
    content: "선물용으로 구매했는데 만족도가 높아요.",
    date: "2025-01-20",
  },
  {
    id: 46,
    productId: 1,
    user: "iu*****",
    rating: 3,
    content: "배송도 빠르고 포장도 꼼꼼했어요.",
    date: "2024-05-19",
  },
  {
    id: 47,
    productId: 1,
    user: "ze*****",
    rating: 1,
    content: "가볍고 편해서 데일리로 딱입니다.",
    date: "2024-12-16",
  },
  {
    id: 48,
    productId: 1,
    user: "th*****",
    rating: 1,
    content: "가격 대비 퀄리티가 좋아요!",
    date: "2024-09-04",
  },
  {
    id: 49,
    productId: 1,
    user: "ir*****",
    rating: 5,
    content: "가격 대비 퀄리티가 좋아요!",
    date: "2024-11-24",
  },
  {
    id: 50,
    productId: 1,
    user: "eo*****",
    rating: 3,
    content: "선물용으로 구매했는데 만족도가 높아요.",
    date: "2025-03-14",
  },
  {
    id: 51,
    productId: 1,
    user: "qt*****",
    rating: 2,
    content: "진짜 예쁜 빨간 가방이에요! 튼튼하고 수납력도 좋아요.",
    date: "2024-11-20",
  },
  {
    id: 52,
    productId: 1,
    user: "no*****",
    rating: 3,
    content: "지퍼 부분이 부드러워서 열고 닫기 편해요.",
    date: "2025-01-17",
  },
  {
    id: 53,
    productId: 1,
    user: "no*****",
    rating: 5,
    content: "선물용으로 구매했는데 만족도가 높아요.",
    date: "2024-08-08",
  },
  {
    id: 54,
    productId: 1,
    user: "bz*****",
    rating: 5,
    content: "가볍고 편해서 데일리로 딱입니다.",
    date: "2025-02-10",
  },
  {
    id: 55,
    productId: 1,
    user: "ks*****",
    rating: 5,
    content: "진짜 예쁜 빨간 가방이에요! 튼튼하고 수납력도 좋아요.",
    date: "2025-01-29",
  },
  {
    id: 56,
    productId: 1,
    user: "ix*****",
    rating: 5,
    content: "지퍼 부분이 부드러워서 열고 닫기 편해요.",
    date: "2025-03-04",
  },
  {
    id: 57,
    productId: 1,
    user: "la*****",
    rating: 3,
    content: "가격 대비 퀄리티가 좋아요!",
    date: "2025-03-19",
  },
  {
    id: 58,
    productId: 1,
    user: "lx*****",
    rating: 4,
    content: "배송도 빠르고 포장도 꼼꼼했어요.",
    date: "2025-01-26",
  },
  {
    id: 59,
    productId: 1,
    user: "dz*****",
    rating: 2,
    content: "진짜 예쁜 빨간 가방이에요! 튼튼하고 수납력도 좋아요.",
    date: "2024-12-15",
  },
  {
    id: 60,
    productId: 1,
    user: "ak*****",
    rating: 5,
    content: "가볍고 편해서 데일리로 딱입니다.",
    date: "2024-11-27",
  },
  {
    id: 61,
    productId: 1,
    user: "qg*****",
    rating: 3,
    content: "지퍼 부분이 부드러워서 열고 닫기 편해요.",
    date: "2025-03-11",
  },
  {
    id: 62,
    productId: 1,
    user: "pj*****",
    rating: 5,
    content: "부담 없이 들기 좋은 스타일이에요.",
    date: "2024-05-17",
  },
  {
    id: 63,
    productId: 1,
    user: "qi*****",
    rating: 1,
    content: "부담 없이 들기 좋은 스타일이에요.",
    date: "2024-12-05",
  },
  {
    id: 64,
    productId: 1,
    user: "ud*****",
    rating: 3,
    content: "진짜 예쁜 빨간 가방이에요! 튼튼하고 수납력도 좋아요.",
    date: "2025-03-16",
  },
  {
    id: 65,
    productId: 1,
    user: "wa*****",
    rating: 1,
    content: "가볍고 편해서 데일리로 딱입니다.",
    date: "2025-05-14",
  },
  {
    id: 66,
    productId: 1,
    user: "ad*****",
    rating: 4,
    content: "옷이랑 잘 어울려서 자주 들게 돼요.",
    date: "2024-12-24",
  },
  {
    id: 67,
    productId: 1,
    user: "cn*****",
    rating: 2,
    content: "옷이랑 잘 어울려서 자주 들게 돼요.",
    date: "2025-04-05",
  },
  {
    id: 68,
    productId: 1,
    user: "sm*****",
    rating: 1,
    content: "진짜 예쁜 빨간 가방이에요! 튼튼하고 수납력도 좋아요.",
    date: "2025-03-17",
  },
  {
    id: 69,
    productId: 1,
    user: "gy*****",
    rating: 3,
    content: "옷이랑 잘 어울려서 자주 들게 돼요.",
    date: "2024-09-06",
  },
  {
    id: 70,
    productId: 1,
    user: "hl*****",
    rating: 1,
    content: "사진보다 실물이 더 예뻐요.",
    date: "2024-07-01",
  },
  {
    id: 71,
    productId: 1,
    user: "jh*****",
    rating: 5,
    content: "옷이랑 잘 어울려서 자주 들게 돼요.",
    date: "2024-05-18",
  },
  {
    id: 72,
    productId: 1,
    user: "mz*****",
    rating: 2,
    content: "배송도 빠르고 포장도 꼼꼼했어요.",
    date: "2024-09-30",
  },
  {
    id: 73,
    productId: 1,
    user: "or*****",
    rating: 3,
    content: "옷이랑 잘 어울려서 자주 들게 돼요.",
    date: "2024-08-10",
  },
  {
    id: 74,
    productId: 1,
    user: "gr*****",
    rating: 4,
    content: "지퍼 부분이 부드러워서 열고 닫기 편해요.",
    date: "2025-04-27",
  },
  {
    id: 75,
    productId: 1,
    user: "xk*****",
    rating: 5,
    content: "선물용으로 구매했는데 만족도가 높아요.",
    date: "2025-02-09",
  },
  {
    id: 76,
    productId: 1,
    user: "fu*****",
    rating: 5,
    content: "가볍고 편해서 데일리로 딱입니다.",
    date: "2024-12-17",
  },
  {
    id: 77,
    productId: 1,
    user: "kt*****",
    rating: 4,
    content: "가격 대비 퀄리티가 좋아요!",
    date: "2025-03-13",
  },
  {
    id: 78,
    productId: 1,
    user: "ge*****",
    rating: 3,
    content: "배송도 빠르고 포장도 꼼꼼했어요.",
    date: "2024-05-29",
  },
  {
    id: 79,
    productId: 1,
    user: "jx*****",
    rating: 1,
    content: "옷이랑 잘 어울려서 자주 들게 돼요.",
    date: "2024-05-23",
  },
  {
    id: 80,
    productId: 1,
    user: "qm*****",
    rating: 1,
    content: "배송도 빠르고 포장도 꼼꼼했어요.",
    date: "2025-04-03",
  },
  {
    id: 81,
    productId: 1,
    user: "en*****",
    rating: 4,
    content: "사진보다 실물이 더 예뻐요.",
    date: "2024-09-02",
  },
  {
    id: 82,
    productId: 1,
    user: "kc*****",
    rating: 2,
    content: "사진보다 실물이 더 예뻐요.",
    date: "2024-07-13",
  },
  {
    id: 83,
    productId: 1,
    user: "av*****",
    rating: 5,
    content: "사진보다 실물이 더 예뻐요.",
    date: "2024-10-15",
  },
  {
    id: 84,
    productId: 1,
    user: "pn*****",
    rating: 4,
    content: "지퍼 부분이 부드러워서 열고 닫기 편해요.",
    date: "2025-04-01",
  },
  {
    id: 85,
    productId: 1,
    user: "vt*****",
    rating: 5,
    content: "가볍고 편해서 데일리로 딱입니다.",
    date: "2025-05-08",
  },
  {
    id: 86,
    productId: 1,
    user: "lz*****",
    rating: 3,
    content: "가죽 질감이 고급스럽고 색감도 마음에 들어요.",
    date: "2024-08-13",
  },
  {
    id: 87,
    productId: 1,
    user: "sn*****",
    rating: 1,
    content: "선물용으로 구매했는데 만족도가 높아요.",
    date: "2024-10-11",
  },
  {
    id: 88,
    productId: 1,
    user: "pr*****",
    rating: 4,
    content: "배송도 빠르고 포장도 꼼꼼했어요.",
    date: "2024-08-21",
  },
  {
    id: 89,
    productId: 1,
    user: "ld*****",
    rating: 1,
    content: "진짜 예쁜 빨간 가방이에요! 튼튼하고 수납력도 좋아요.",
    date: "2024-11-14",
  },
  {
    id: 90,
    productId: 1,
    user: "iq*****",
    rating: 4,
    content: "옷이랑 잘 어울려서 자주 들게 돼요.",
    date: "2025-04-11",
  },
  {
    id: 91,
    productId: 1,
    user: "ag*****",
    rating: 4,
    content: "가볍고 편해서 데일리로 딱입니다.",
    date: "2025-02-19",
  },
  {
    id: 92,
    productId: 1,
    user: "co*****",
    rating: 4,
    content: "지퍼 부분이 부드러워서 열고 닫기 편해요.",
    date: "2025-02-10",
  },
  {
    id: 93,
    productId: 1,
    user: "yz*****",
    rating: 4,
    content: "진짜 예쁜 빨간 가방이에요! 튼튼하고 수납력도 좋아요.",
    date: "2025-02-11",
  },
  {
    id: 94,
    productId: 1,
    user: "ms*****",
    rating: 1,
    content: "부담 없이 들기 좋은 스타일이에요.",
    date: "2024-08-04",
  },
  {
    id: 95,
    productId: 1,
    user: "de*****",
    rating: 2,
    content: "가볍고 편해서 데일리로 딱입니다.",
    date: "2025-05-09",
  },
  {
    id: 96,
    productId: 1,
    user: "jd*****",
    rating: 1,
    content: "부담 없이 들기 좋은 스타일이에요.",
    date: "2024-06-12",
  },
  {
    id: 97,
    productId: 1,
    user: "pe*****",
    rating: 2,
    content: "선물용으로 구매했는데 만족도가 높아요.",
    date: "2024-08-31",
  },
  {
    id: 98,
    productId: 1,
    user: "eh*****",
    rating: 1,
    content: "가죽 질감이 고급스럽고 색감도 마음에 들어요.",
    date: "2024-11-15",
  },
  {
    id: 99,
    productId: 1,
    user: "wx*****",
    rating: 1,
    content: "부담 없이 들기 좋은 스타일이에요.",
    date: "2025-01-20",
  },
  {
    id: 100,
    productId: 1,
    user: "gg*****",
    rating: 3,
    content: "진짜 예쁜 빨간 가방이에요! 튼튼하고 수납력도 좋아요.",
    date: "2025-04-08",
  }
];